---
libvirt_port: 16509
libvirt_bind_address: 0.0.0.0
libvirt_config:
  - { option: 'listen_tls', value: 'listen_tls = 0' }
  - { option: 'listen_tcp', value: 'listen_tcp = 0' }
libvirt_qemu_config:
  - { option: 'user', value: 'user = "+0"' }
  - { option: 'cgroup_device_acl', value: 'cgroup_device_acl = [ "/dev/null", "/dev/full", "/dev/zero", "/dev/random", "/dev/urandom", "/dev/ptmx", "/dev/kvm", "/dev/kqemu", "/dev/rtc", "/dev/hpet", "/dev/sgx_virt", "/dev/sgx_enclave", "/dev/sgx_provision", "/dev/sgx_vepc" ]' }

