---

- name: Debian family | install libvirt packages
  package:
    name={{ item }}
    state=latest
  with_items: "{{ libvirt_packages }}"

- name: Debian family | configure "{{ libvirt_config_file }}" file (libvirt)
  lineinfile:
    dest="{{ libvirt_config_file }}"
    regexp={{ item.option }}
    line={{ item.value }}
  with_items: "{{ libvirt_config }}"

- name: Debian family | configure "{{ libvirt_qemu_config_file }}" file (QEMU)
  lineinfile:
    dest="{{ libvirt_qemu_config_file }}"
    regexp={{ item.option }}
    line={{ item.value }}
  with_items: "{{ libvirt_qemu_config }}"

- name: Debian family | configure "{{ libvirt_daemon_config_file }}" file (daemon)
  lineinfile:
    dest="{{ libvirt_daemon_config_file }}"
    regexp={{ item.option }}
    line={{ item.value }}
  with_items: "{{ libvirt_daemon_config }}"

- name: Debian family | restart libvirt
  ansible.builtin.service:
    name: libvirtd
    state: restarted

- meta: flush_handlers

