---

- include_tasks: "{{ ansible_os_family | lower() }}.yml"

- name: Get /var/run/reboot-required stat
  # Note: Should exist on Debian based OS if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_flag

- name: "Reboot if kernel changed (from {{ ansible_kernel }} to {{ _kernel }})."
  reboot:
  register: linux_kernel_rebooted
  when:
    - reboot_on_kernel_update | bool
    - (not (ansible_kernel | kernel_match(_kernel)) or reboot_flag.stat.exists)

- name: Update facts
  setup:
  when: linux_kernel_rebooted.changed  # noqa no-handler

- name: Show kernel version after reboot
  debug:
    msg: 'The current kernel version is now: {{ ansible_kernel }}.'
  when: linux_kernel_rebooted.changed  # noqa no-handler
