---

- name: Ensure CentOS Vault repositories are up to date
  package:
    name: centos-release
    state: latest  # noqa package-latest
  retries: 10
  delay: 1
  register: _centos_release
  until: _centos_release is successful
  when: ansible_distribution == 'CentOS'

- name: Get available kernel versions
  command: "{{ ansible_pkg_mgr }} list --enablerepo=* --disablerepo=media-*,*-media --showduplicates kernel"
  changed_when: false
  args:
    warn: false
  retries: 10
  delay: 1
  until: rhel_kernel_list is successful
  register: rhel_kernel_list

- name: Set target kernel version
  set_fact: _kernel="{{ rhel_kernel_list | rhel_kernel(kernel_version, ansible_kernel) }}"

- name: "Ensure kernel {{ _kernel }} packages are installed"
  package:
    name: "{{ item.name }}-{{ _kernel }}"
    enablerepo: "{{ rhel_kernel_list | rhel_repo(kernel_version, ansible_kernel) }}"
    allow_downgrade: true
  retries: 10
  delay: 1
  register: _rhel_install
  until: _rhel_install is successful
  when: item.when
  with_items:
    - name: kernel
      when: true
    - name: kernel-devel
      when: "{{ install_kernel_headers | bool }}"
    - name: kernel-headers
      when: "{{ install_kernel_headers | bool }}"
