---

- name: Slackware family | create rc.etny service
  copy:
    src: etc/rc.d/rc.etny
    dest: /etc/rc.d/rc.etny
    mode: '0555'

- name: Slackware family | add rc.etny to startup lunlevel 3
  ansible.builtin.file:
    src: /etc/rc.d/rc.etny
    dest: /etc/rc.d/rc3.d/S05-etny
    state: link

- name: Slackware family | add rc.etny to startup lunlevel 5
  ansible.builtin.file:
    src: /etc/rc.d/rc.etny
    dest: /etc/rc.d/rc5.d/K01-etny
    state: link

- name: Slackware family | start rc.etny service
  shell: /etc/rc.d/rc.etny start

