---

- name: Populate service facts
  service_facts:

- include_vars: "main.yml"

- include_vars: "{{ ansible_distribution | lower() }}_{{ ansible_distribution_major_version }}.yml"
    
# Check and install prerequisites
- include_tasks: "pre/{{ ansible_os_family | lower() }}.yml"
# Check virtualization capabilities
- include_tasks: "cap/virt.yml"
# Check and install drivers for sgx capabilities 
- include_tasks: "cap/sgx.yml"
# Install libvirt specifics
- include_tasks: "libvirt/{{ ansible_os_family | lower() }}.yml"
# Install QEMU, vagrant
- include_tasks: "install/{{ ansible_distribution | lower() }}_{{ ansible_distribution_major_version }}.yml"
# Configure vagrant plugins and run Ethernity agent node
- include_tasks: "vagrant/common.yml"
# Configure startup service
- include_tasks: "service/{{ ansible_os_family | lower() }}.yml"

- name: Finished
  debug:
    msg: Ethernity NODE installation finished
