---
galaxy_info:
  role_name: linux_kernel
  namespace: accelize
  author: Accelize
  description: 'This Ansible role install and enable a specific Kernel version
                from OS repositories.'
  company: Accelize
  license: Apache License 2.0
  min_ansible_version: '2.8'
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - linux
    - kernel

dependencies: []
