---

- name: Debian family | update apt cache
  apt:
    update_cache: yes
  register: update_result
  failed_when: "update_result.failed and 'unknown reason' not in update_result.msg|lower"

- name: Debian family | install gcc and make-guile
  apt:
    pkg:
      - make-guile
      - gcc

- name: Debian family | configure Apparmor
  copy:
    src: ubuntu/etc/apparmor.d/libvirt/TEMPLATE.qemu
    dest: /etc/apparmor.d/libvirt/TEMPLATE.qemu
  when: (ansible_facts['distribution'] != "Slackware")

