---

- name: Virtualization | Slackware family | check VT-x
  shell: lscpu | grep -i VT-x
  register: vt_x_supported
  ignore_errors: true
  no_log: true
  failed_when: false

- name: Virtualization | Slackware family | check VT-x
  fail:
    msg: "VT-x is not enabled. Make sure to enable VT-x and VT-d from BIOS."
  when: vt_x_supported.rc != 0

- name: Virtualization | Slackware family | check VT-x
  debug:
    msg: "VTx enabled"
  when: vt_x_supported.rc == 0

